"use client";

import { motion } from "framer-motion";
import {
  BrainCircuit,
  Mic,
  FileText,
  CheckCircle2,
  ArrowRight,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const steps = [
  {
    title: "Upload Job Context",
    desc: "Paste your job description and position. Our AI analyzes the requirements to tailor the interview.",
    icon: <FileText className="h-8 w-8 text-primary" />,
    color: "bg-primary/10",
  },
  {
    title: "AI Interview Session",
    desc: "Engage in a live, voice-enabled interview with our AI coach. Experience realistic situational questions.",
    icon: <Mic className="h-8 w-8 text-secondary" />,
    color: "bg-secondary/10",
  },
  {
    title: "Instant AI Evaluation",
    desc: "Get immediate ratings and detailed feedback for every answer you provide during the session.",
    icon: <BrainCircuit className="h-8 w-8 text-primary" />,
    color: "bg-primary/10",
  },
  {
    title: "Master the Results",
    desc: "Review 'Ideal Answers' generated by the AI to understand how to improve your performance.",
    icon: <CheckCircle2 className="h-8 w-8 text-emerald-500" />,
    color: "bg-emerald-500/10",
  },
];

export default function HowItWorks() {
  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="relative overflow-hidden py-24 sm:py-32">
        <div className="absolute top-0 -left-4 h-72 w-72 rounded-full bg-primary/5 blur-3xl" />
        <div className="absolute bottom-0 -right-4 h-72 w-72 rounded-full bg-secondary/5 blur-3xl" />

        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="text-4xl font-extrabold tracking-tight sm:text-6xl"
            >
              How it <span className="text-primary italic">Works</span>
            </motion.h1>
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="mt-6 text-lg leading-8 text-muted-foreground"
            >
              Mastering your interview shouldn&apos;t be a mystery. MockMate AI
              breaks down the process into four simple, effective steps.
            </motion.p>
          </div>

          <div className="mt-20 grid gap-12 lg:grid-cols-4">
            {steps.map((step, idx) => (
              <motion.div
                key={step.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.1 + 0.2 }}
                className="relative flex flex-col items-center text-center group"
              >
                <div
                  className={`mb-8 flex h-20 w-20 items-center justify-center rounded-2xl ${step.color} shadow-inner transition-transform group-hover:scale-110`}
                >
                  {step.icon}
                </div>
                <h3 className="mb-4 text-xl font-bold">{step.title}</h3>
                <p className="text-muted-foreground leading-relaxed">
                  {step.desc}
                </p>
                {idx < steps.length - 1 && (
                  <div className="hidden lg:block absolute top-10 left-[calc(50%+4rem)] w-[calc(100%-8rem)] border-t-2 border-dashed border-primary/20" />
                )}
              </motion.div>
            ))}
          </div>

          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.6 }}
            className="mt-24 p-8 rounded-3xl bg-slate-50 dark:bg-slate-900/50 border border-primary/5 text-center"
          >
            <h2 className="text-3xl font-bold mb-6 italic underline decoration-primary">
              Ready to Ace Your Next Interview?
            </h2>
            <Button
              size="lg"
              className="h-14 px-10 text-lg font-bold shadow-xl shadow-primary/20"
              asChild
            >
              <Link href="/dashboard">
                Get Started Now <ArrowRight className="ml-2 h-5 w-5" />
              </Link>
            </Button>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
